language: node_js
node_js: node
services: mongodb
jobs:
  include:
  - stage: Package release
    if: tag IS present
    before_deploy:
    - npm run package
    deploy:
      skip_cleanup: true
      provider: releases # When there is a tag, pack api and upload tar.gz.
      token:
        secure: TzC1MbuGz1AKSxzrDMWHqfd+S3XmUERZfmfa0G+RX7CMJwD85c4LAorYN4lAsdT7LEi1BfRvDT7ceSf5+YQi8CvMjAUzjhHMtGFoKCIscUkcwC/X20Y80S64vwIBNX0q5in9CMR6f5OV9v+UIswKUwZ4uKRWGQFmhy8/nsQ64FNDlwhRhROPjNZSME44iYLLErICGjNdG0j4G5uLjSPbDMqRqtnXuCQfcYVkX9fMBvLY27BROfgW2eaMCIYF4RbL0f0ftizQkgnqifpCVQUDcPLOjAJ2eOPrFKqJyWrdIhRpmyo2g2DexAdMeXC9VzDX38hFmFDiyJBpFEbXRBYfG/S/WclpKdjAH6Ml4QiAVz86ck7Ku7tzZ4x7NfRBm1R3CuIvFWesYYQ8XuL1inQSDoQMGfw46J+uCJIRBAh7loZwjvY59sNamLgzpAFcYhz6eJbguMMtPTQCqO2UkNm3UarqbOQX7EtyGyNixyUpJA6mBJ1d6gT7F0vABiruk3WB6xpm3beFKdPCJ90wqoUGzpKaEMgc1EWu+xc/LFlFyZfWSYVp/2Qclnt9vYoQVYZs8ywqer3H8K5aF6fDfs+4ntX40BOeiWXt6NFxeHQp3LavVw05vGFJvjYgTt3hLdwf/IQJR5GqQ2bLUwNeRp4LH+m2gRvr1hpwJjfw7OvguBE=
      file:
      - pilasbloques-api.tar.gz
      on:
        tags: true
        all_branches: true