language: node_js
node_js: node
services: mongodb
jobs:
  include:
  - stage: Package release
    if: tag IS present
    before_deploy:
    - npm run package
    deploy:
      skip_cleanup: true
      provider: releases
      token:
        secure: Y36o8zYMmuEeiE0Ycfeay6AuH9UfjWg0YuYWV7VcviH9Wvpp20x+MuiOYqIgdP35AM7Pw0qnjO100UjPhcWAzqZsGo23nOX41LGSUvlm87P/RNK4NOcvBvUxON2effgF8X1ue+oqJd1vPMVQ7wi0rV6GtkeEEzYJ1xGpiEMvI4Ynd0bemSVLRHXn2tol0f8XWoBlfWi8nyNS72Fp4Xk0Jy1WhXd7mypmlDwj3c8FRgDAcMwjK8rLUAFjiYKjkS5gir2qZAWGUGCPkJai/4s4LWBvenaVM2zpV4i3Uf3hZcznwC12ZXs+sB1Pn5VwnXI5lrbX6MsUVH6dnd6nqYqeA9UCfPqwB35KVU72Lll14RgxmYiru2/3th7sM4qkEPn9ZEKmZmXukoEYu6igBPnVCpre7nzZaw2oq23GYwMKTreq2EMQFFO1hTuXyp7Aqu8Qy52lU2ia72c6AU7TXxHuCsaD3Pnd85ztTJXwyXKrZ7CYnBmkQ9p1h1f9MrdICHxel1amgea1yI/xhLYCZoJR3upS30R2hn2mYeVVvFpDzIiFuAPTf/UC60kjvKfFB9PZ5UM7xvV4zSTg1Z+bqZLATxLsb4sSp2seG7bMG2+kXkRFYAFqmj5fnxoziIBzZFvfVXGNRfhWswPok77z7LC21HV0PGy5edYwwuaA8juup+8=
      file:
      - pilasbloques-api.tar.gz
      on:
        tags: true
        all_branches: true
