language: node_js
node_js: node
services: mongodb
jobs:
  include:
  - stage: Package release
    if: tag IS present
    before_deploy:
    - npm run package
    deploy:
      skip_cleanup: true
      provider: releases # When there is a tag, pack api and upload tar.gz.
      file:
      - pilasbloques-api.tar.gz
      on:
        tags: true
        all_branches: true
env:
  global:
    secure: WvD/OKN7GTFoECSUDqHyMvj0qKtVR9Uj2h8FBPZSrIqEna9kxu+9PFsVN1DXtRZgCQzrz5tZgGDR6DbJuWOa1gQG8fzbtS+t5Qp6zy+ECLJEGIQ/6AuSUkMMKtqevjCaJFArYFgGTzZ6PgDgPQj5+qX359jfJefqL5kvnLM4mZaMwWSF2Jgqgms04zhvKSR/LeyQNyIr+FxGWIB5hHTbSRIE3aMWOztXuvzi6HkXDvms2I1UBBcJh2SFFpQbwVcTFuyHISccthfiCNGpW8vegZ6ZuNmo4wQZOLTPC0MyW6JsKjq07w6qcSN9YTKYagGWwWpRl8TlODX2KhCSgQS6MWtWyDgMdKc5QiaL00dgYQqlaMGasmxFUD4b8UPj720kb1jOK/+w9qGoNz78VVdczddn62c3dWzBVaOlqQyKsSiuy5r61hpJfkH6eNmV12NJDHb0FWHqo1WQiVnkLB32bia2sA3Ly17qzy5qH4rZ7JdNA+K42Oi+mFEzPhBbbGiJtbPXRfLCZt/HtkgamWA9mHdHWIL/25aP71lMwdK8er8Y98Oh9xZG0V6mFq9D7zAi33oAjbcnZqoKo9aaEZgEIXCvtWAuzAo3DBNGTgfooLkUEqtcWibtvH38mWPMVPfg82NwNB3uCI47nyrlPHYHpNV8P5YZ8rt+QJqtmKd7vaM=
