#copypasted from https://github.com/Program-AR/pilas-bloques/blob/develop/.github/workflows/build.yml
name: build
on: 
  push:
  release:
   types:
    - released
jobs:
  test:
    uses: Program-AR/pilas-bloques/.github/workflows/test_prueba.yml@12e1988d002cab40757efb91747fd8397aef7806

  package-release:
    if: github.event_name == 'release'
    needs: test
    uses: Program-AR/pilas-bloques/.github/workflows/release.yml@f7c0f65b070b3ce1af26230f9dd122e2256d09a1
    with:
      asset_name: pilasbloques-api.tar.gz
      asset_path: ./pilasbloques-api.tar.gz
        
